version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: wweb_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql/conf/conf.d:/etc/mysql/conf.d
      - ./mysql/conf/init.d:/docker-entrypoint-initdb.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    networks:
      - wwebnet

  # postgres:
  #   image: postgres:latest
  #   container_name: wweb_postgres
  #   ports: 
  #     - 5432:5432
  #   environment: 
  #     - POSTGRES_USER=${DB_USER}  
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   volumes:
  #     - postgresdata:/var/lib/postgresql/data
  #   networks:
  #     - wwebnet

  redis:
    image: redis:latest
    container_name: wweb_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - wwebnet

  web:
    build: ./cmd/wweb
    container_name: wweb_web
    ports:
      - ${PORT}:8080
    environment: 
      - DB_HOST=${DB_HOST}
      - DB_DRIVER=${DB_DRIVER} 
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT} 
    restart: on-failure
    volumes:
      - ./cmd/wweb/logs:/wweb/logs
    depends_on:
      - mysql
 #     - postgres
      - redis
    networks:
      - wwebnet


volumes:
  wwebdata: {}
  mysqldata: {}
 # postgresdata: {}
  redisdata: {}

networks:
  wwebnet:
    driver: bridge